### ISSUE TITLE
Arch package

### ISSUE THREAD

**Issue by andrei-pavel** [prakashdanish/goodreadsh#1]
Could you create an Arch package so that Arch users can easily install it with an AUR helper?

Wrote a working PKGBUILD which is really all that is needed.
```
# Maintainer: Danish Prakash <EMAIL HERE>
_gitrepository='goodreadsh'
_gitbranch='master'
pkgname='goodreadsh-git'
pkgver=1.16 # <ACTUAL VERSION HERE>
pkgrel=1
pkgdesc='Command line interface for Goodreads'
arch=('i686' 'x86_64')
url='https://github.com/prakashdanish/goodreadsh'
license=('MIT')
depends=()
makedepends=('git')
provides=('goodreadsh')
source=("git+https://github.com/prakashdanish/${_gitrepository}.git#branch=${_gitbranch}")
md5sums=('SKIP')

pkgver() {
  cd "${_gitrepository}"
  printf '1.%s\n' "$(( $(git rev-list --count master) ))"
}

package() {
  cd "${srcdir}/${_gitrepository}"
  install -Dm755 './goodreads' "${pkgdir}/usr/local/bin/goodreads"
}
```

**Comment by danishprakash** [comment]
@andrei-pavel will test this on my system soon. Thanks for this, although I don't have much experience with maintaining with arch packages, is this all there is to it?

**Comment by andrei-pavel** [comment]
You only do it once and then if you want to be pedantic, so that the package is not out of date, for every push in the master branch of goodreadsh, you would push in the AUR repository with a version change. However even if it shows out of date, the package will install right away with the latest version.
Here are a few steps:
1. Create an AUR account if you don't have one.
2. Create an AUR repository which is a git repository on that account. You can put your public SSH key for convenience.
3. Write the PKGBUILD above.
4. Run makepkg --printsrcinfo > .SRCINFO
5. commit and push PKGBUILD AND .SRCINFO and you're done
To test installation, there's a makepkg argument that installs on your system like you would use an AUR helper

Also, another user could also do this in your place, no problem

Thank you for all you do!

**Comment by danishprakash** [comment]
Thanks for all the help there, I have a couple of questions regarding the PKGBUILD

- the wiki says avoid using `/usr/local` for installation.
- is it required to add `-git` as a suffix? (couldn't find this in the wiki)

I came up with this PKGBUILD based on yours

```sh
# Maintainer: Danish Prakash <danishprakash@outlook.com>
_gitrepository='goodreadsh'
_gitbranch='master'
pkgname='goodreadsh'
pkgver=1.16
pkgrel=1
pkgdesc='Command line interface for Goodreads'
arch=('i686' 'x86_64')
url='https://github.com/prakashdanish/goodreadsh'
license=('MIT')
depends=()
makedepends=('git')
provides=('goodreadsh')
source=("git+https://github.com/prakashdanish/${_gitrepository}.git#branch=${_gitbranch}")
md5sums=('SKIP')

pkgver() {
  cd "${_gitrepository}"
  printf '1.%s\n' "$(( $(git rev-list --count master) ))"
}

package() {
  cd "${srcdir}/${_gitrepository}"
  install -Dm755 './goodreads' "${pkgdir}/usr/bin/goodreads"
}
```

Edit: could you test [this](https://aur.archlinux.org/packages/goodreadsh/) before I add the relevant info to the readme?

**Comment by andrei-pavel** [comment]
Yep, I succesfully installed it on my system with `yay -S --noconfirm goodreadsh`. :smile: Thank you so much!
* I had no indea `/usr/local` should be avoided.
* There is this piece of documentation[1] about `foo-git` packages and I remember I received an error or at least a warning when I had not suffixed one of my packages with `-git`, but this seems to work just fine and is definitely preferred in terms of aesthetics so I would just leave it like this. `¯\_(ツ)_/¯`

[1] https://wiki.archlinux.org/index.php/Arch_User_Repository#What_is_the_difference_between_foo_and_foo-git_packages.3F

**Comment by danishprakash** [comment]
That's great! Closing this now.
